FROM nginx

COPY nginx.config /etc/nginx/conf.d/default.conf
COPY tmp/index.html /usr/share/nginx/html
COPY tmp/install.js /usr/share/nginx/html
COPY tmp/install.svg /usr/share/nginx/html
COPY tmp/Kotlin-logo.svg /usr/share/nginx/html
COPY tmp/KotlinMppReact.js /usr/share/nginx/html
COPY tmp/main.css /usr/share/nginx/html
COPY tmp/manifest.json /usr/share/nginx/html
COPY tmp/offline.html /usr/share/nginx/html
COPY tmp/service-worker.js /usr/share/nginx/html
COPY tmp/images /usr/share/nginx/html/images
COPY tmp/favicon.ico /usr/share/nginx/html
