FROM nginx

COPY nginx.config /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html
COPY install.js /usr/share/nginx/html
COPY install.svg /usr/share/nginx/html
COPY Kotlin-logo.svg /usr/share/nginx/html
COPY KotlinMppReact.js /usr/share/nginx/html
COPY main.css /usr/share/nginx/html
COPY manifest.json /usr/share/nginx/html
COPY offline.html /usr/share/nginx/html
COPY service-worker.js /usr/share/nginx/html
COPY images /usr/share/nginx/html/images
COPY favicon.ico /usr/share/nginx/html
